language: node_js
node_js:
  - 14

services: 
  - docker

before_script: 
  - npm install

script:
  - docker build -t udagram-api-feed ./udagram-api-feed

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram--api-feed:latest
  - docker push $DOCKER_USERNAME/udagram-api-feed:latest