language: node_js
node_js:
  - 14

sudo: required

services: 
  - docker

before_script: 
  - npm install

script:
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:latest
  - docker push $DOCKER_USERNAME/udagram-reverseproxy:latest
  