language: node_js
node_js:
  - 14

services: 
  - docker

before_script: 
  - npm install

script:
  - docker build -t udagram-api-user ./udagram-api-user

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:latest
  - docker push $DOCKER_USERNAME/udagram-api-user:latest